activities/urls.py
from django.urls import path
from . import views

app_name = 'activities'

urlpatterns = [
    path('', views.activities, name='activities'),
    path('add/', views.add_activity, name='add_activity'),
    path('<int:activity_id>/add-activity-member/', views.add_activity_member, name='add_activity_member'),
    path('delete/<int:member_id>/', views.delete_member, name='delete_member'),
]

matakuliah/urls.py
from django.urls import path, re_path
from . import views

app_name = 'matakuliah'

urlpatterns = [
    path('', views.matkul, name='matkuls'),
    path('add/', views.create_matkul, name='create_matkul'),
    path('<int:matkul_id>/', views.detail_matkul, name='detail_matkul'),
    path('delete/', views.delete, name='delete'),
    path('delete/<int:matkul_id>/', views.delete_matkul, name='delete_matkul'),
]

myprofile/urls.py
from django.urls import path, re_path
from . import views

app_name = 'myprofile'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects, name='projects'),
    path('time/', views.time, name='time'),
    re_path(r'^time/((?P<plus>-?\d+)/)?$', views.time, name='time'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myprofile.urls', namespace='myprofile')),
    path('story1/', include('story1.urls', namespace='story1')),
    path('matakuliah/', include('matakuliah.urls', namespace='matakuliah')),
    path('activities/', include('activities.urls', namespace='activities')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='story1index'),
]

activities/models.py
from django.db import models

class Activity(models.Model):

    def __str__(self):
        return self.nama_kegiatan

    nama_kegiatan = models.CharField(max_length=150)
    deskripsi_singkat_kegiatan = models.CharField(max_length=300)

class ActivityMember(models.Model):
    
    def __str__(self):
        return self.nama_peserta

    kegiatan = models.ForeignKey(Activity, on_delete=models.CASCADE)
    nama_peserta = models.CharField(max_length=100)

matakuliah/models.py
from django.db import models
from .choices import *

class Matkul(models.Model):

    def __str__(self):
        return self.nama_mata_kuliah

    nama_mata_kuliah = models.CharField(max_length=200)
    dosen = models.CharField(max_length=200)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    semester = models.CharField(max_length=100, choices=SEMESTER_CHOICES, default='Gasal')
    tahun_ajar = models.CharField(max_length=100, choices=TAHUN_CHOICES, default='2019/2020')
    ruang = models.CharField(max_length=100)

class Tugas(models.Model):

    def __str__(self):
        return self.tugas

    mata_kuliah = models.ForeignKey(Matkul, on_delete=models.CASCADE)
    tugas = models.TextField(max_length=200)
    deadline = models.DateTimeField()

myprofile/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

activities/forms.py
from django import forms
from .models import Activity, ActivityMember

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['nama_kegiatan', 'deskripsi_singkat_kegiatan']

class ActivityMemberForm(forms.ModelForm):
    class Meta:
        model = ActivityMember
        fields = ['nama_peserta']

matakuliah/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['nama_mata_kuliah', 'dosen', 'jumlah_sks', 'deskripsi', 'semester', 'tahun_ajar', 'ruang']

activities/views.py
from django.shortcuts import render, redirect
from .models import Activity, ActivityMember
from .forms import ActivityForm, ActivityMemberForm

def activities(request):
    activities = Activity.objects.all()
    members = ActivityMember.objects.all()
    return render(request, 'activities/activities.html', {'activities': activities, 'members': members})

def add_activity(request):
    add_activity_form = ActivityForm(request.POST or None)
    if add_activity_form.is_valid():
        add_activity_form.save()
        return redirect('activities:activities')
    return render(request, 'activities/add-activity.html', {'add_activity_form': add_activity_form})

def add_activity_member(request, activity_id):
    activity = Activity.objects.get(id=activity_id)
    add_member_form = ActivityMemberForm(request.POST or None)
    if add_member_form.is_valid():
        add_member = add_member_form.save(commit=False)
        add_member.kegiatan = activity
        add_member.save()
        return redirect('activities:activities')
    return render(request, 'activities/add-activity-member.html', {'add_member_form': add_member_form, 'activity': activity})

def delete_member(request, member_id):
    member = ActivityMember.objects.get(id=member_id)
    if request.method == 'POST':
        member.delete()
        return redirect('activities:activities')

    return render(request, 'activities/activites.html')
    

matakuliah/views.py
from django.shortcuts import render, redirect
from .models import Matkul, Tugas
from .forms import MatkulForm
from datetime import datetime, timedelta

def matkul(request):
    matkuls = Matkul.objects.all()
    return render(request, 'matakuliah/matkul.html', {'matkuls': matkuls})

def create_matkul(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('matakuliah:matkuls')
    return render(request, 'matakuliah/matkul-form.html', {'form': form})

def detail_matkul(request, matkul_id):
    detail = Matkul.objects.get(id=matkul_id)
    tugas_matkul = Tugas.objects.filter(mata_kuliah=detail).order_by('deadline')
    #now = datetime.now()
    #prev_day = timedelta(1)
    #prev_days = timedelta(365)
    return render(request, 'matakuliah/detail.html', {'detail': detail, 'tugas_matkul': tugas_matkul})

def delete(request):
    matkuls = Matkul.objects.all()
    return render(request, 'matakuliah/delete.html', {'matkuls': matkuls})

def delete_matkul(request, matkul_id):
    matkul = Matkul.objects.get(id=matkul_id)
    if request.method == 'POST':
        matkul.delete()
        return redirect('matakuliah:delete')
    return render(request, 'matakuliah/delete-confirm.html', {'matkul': matkul})

myprofile/views.py
from django.shortcuts import render
from django.utils import timezone as tz
from datetime import timedelta

def index(request):
    return render(request, 'myprofile/index.html')

def projects(request):
    return render(request, 'myprofile/projects.html')

def time(request, plus=0):
    tz.activate('Asia/Jakarta')
    now = tz.now()
    time = now + timedelta(hours=int(plus))
    return render(request, 'myprofile/time.html', {'time': time})

story1/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story1/index.html')

activities/templates/activities/activities.html
{% extends 'myprofile/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Gita's Activities {% endblock %}

{% block content %}

<div class="activities">

    {% include 'myprofile/navbar.html' %}

    <h1>Activities</h1>
    <p>Join me do some activities by putting your name on the list(s).</p>
    <a class="btn btn-add-activity mb-4" href="{% url 'activities:add_activity' %}">Add an Activity</a>


    <div class="row">
        {% for activity in activities %}
        <div class="col-lg-4 col-md-6">
            <div class="card activity-column">
                <div class="card-header">
                    <h3>{{ activity.nama_kegiatan }}</h3>
                </div>
                <div class="card-body">
                    <h5>{{ activity.deskripsi_singkat_kegiatan }}</h5><br>

                    <p class="participants">Participants:</p>

                    {% for member in members %}
                    {% if member.kegiatan == activity %}
                    <ul>
                        <div class="row">
                            <div class="col">
                                <li>{{ member.nama_peserta }}</li>
                            </div>
                            <div class="col">
                                <div class="float-right">
                                    <form method="POST"
                                        action="{% url 'activities:delete_member' member.id %}">
                                        {% csrf_token %}
                                        <button type="submit">&times;</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </ul>
                    {% endif %}
                    {% endfor %}

                    <a class="btn btn-activity" href="{% url 'activities:add_activity_member' activity.id %}">I want to
                        join</a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

activities/templates/activities/add-activity-member.html
{% extends 'myprofile/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Join me on {{ activity.nama_kegiatan }} {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="add-activity">

        {% include 'myprofile/navbar.html' %}

        <div class="add-activity-900">

            <h1>Join me on {{ activity.nama_kegiatan }}</h1><br>

        <h4>{{ activity.deskripsi_singkat_kegiatan }}</h4><br>

        <div class="add-activity-form">
            <form method="POST">
                {% csrf_token %}
                <div class="main-content-form container-fluid">
                    <div class="form-group">
                        {{ add_member_form }}
                    </div>
                    <button type="submit" class="btn btn-add-activity">Add me to the list!</button>
                </div>
            </form>
        </div>

        </div>

    </div>

</div>


{% endblock %}

activities/templates/activities/add-activity.html
{% extends 'myprofile/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Add an Activity {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="add-activity">

        {% include 'myprofile/navbar.html' %}

        <div class="add-activity-900">
            <h1>Add an Activity</h1>
            <div class="add-activity-form">
                <form method="POST">
                    {% csrf_token %}

                    {{ add_activity_form|crispy }}

                    <button type="submit" class="btn btn-add-activity">Add</button>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

matakuliah/templates/matakuliah/delete-confirm.html
{% extends 'myprofile/base.html' %}

{% block title %}Delete Matkul {{ matkul.nama_mata_kuliah }}{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="matkul">

        <!-- Nav Bar -->
        {% include 'myprofile/navbar.html' %}
        
        <form method="POST">
            {% csrf_token %}
            <h3>Are you sure you want to delete {{ matkul.nama_mata_kuliah }}?</h3>
            <center><button class="btn btn-danger" type="submit">Confirm</button>
            <a href="{% url 'matakuliah:delete' %}" class="btn btn-primary">Go Back</a></center>
        </form>
            
    </div>
</div>

{% endblock %}

matakuliah/templates/matakuliah/delete.html
{% extends 'myprofile/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Delete Mata Kuliah{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="matkul">

        <!-- Nav Bar -->
        {% include 'myprofile/navbar.html' %}

        <h1>Delete Mata Kuliah</h1>

        {% for matkul in matkuls %}
        <ul class="list-matkul list-matkul-delete">
            
            <div class="row">
                <div class="col-md-10">
                    <h4><a class="matkul-title" href="{% url 'matakuliah:detail_matkul' matkul.id %}">{{ matkul.nama_mata_kuliah }} ({{ matkul.jumlah_sks }} SKS)</a></h4>
                    <p><a class="matkul-attr">Dosen: </a>{{ matkul.dosen }}</p>
                </div>
                <div class="col-md-2 details-btn">
                    <a href="{% url 'matakuliah:delete_matkul' matkul.id %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
            
        </ul>
        {% endfor %}
    </div>
</div>

{% endblock %}

matakuliah/templates/matakuliah/matkul-form.html
{% extends 'myprofile/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Tambah Mata Kuliah Gita{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="matkul-form">

        <!-- Nav Bar -->
        {% include 'myprofile/navbar.html' %}

        <h3>Tambah Mata Kuliah</h3>

        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-add-activity">Tambah</button>
        </form>
    </div>
</div>

{% endblock %}

matakuliah/templates/matakuliah/matkul.html
{% extends 'myprofile/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Mata Kuliah Gita{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="matkul">

        <!-- Nav Bar -->
        {% include 'myprofile/navbar.html' %}

        <h1>Mata Kuliah</h1>

        <div class="add-delete">
            <a href="{% url 'matakuliah:create_matkul' %}" class="btn btn-matkul">Add Mata Kuliah</a>
            <a href="{% url 'matakuliah:delete' %}" class="btn btn-matkul">Delete Mata Kuliah</a>
        </div>

        {% for matkul in matkuls %}
        <ul class="list-matkul">

            <div class="row">
                <div class="col-md-10">
                    <h4><a class="matkul-title"
                            href="{% url 'matakuliah:detail_matkul' matkul.id %}">{{ matkul.nama_mata_kuliah }}
                            ({{ matkul.jumlah_sks }} SKS)</a></h4>
                    <p><a class="matkul-attr">Dosen: </a>{{ matkul.dosen }}</p>
                </div>
                <div class="col-md-2 details-btn">
                    <a href="{% url 'matakuliah:detail_matkul' matkul.id %}" class="btn">Details</a>
                </div>
            </div>

        </ul>
        {% endfor %}
    
    </div>
</div>

{% endblock %}

myprofile/templates/myprofile/index.html
{% extends 'myprofile/base.html' %}
{% load static %}
{% block title %}Gita's Website{% endblock %}
{% block content %}

<!-- Header -->
<header>
    <div class="container-fluid">
        <div class="header">

            <!-- Nav Bar -->
            {% include 'myprofile/navbar.html' %}

            <!--<img src="https://drive.google.com/uc?id=1HgbDT_VrmozVHSkXlsoxh7k9vSaLHuN1" alt="Gita" width="200">-->
            <div class="header-content">
                <h1>Hello, I'm Gita</h1>
                <p>Computer Science Student</p>
                <br>
                <a class="btn btn-outline-light" href="#desc" role="button"><i
                        class="fas fa-angle-double-down"></i></a>
            </div>

        </div>
    </div>
</header>

<!-- Description -->
<section id="desc">
    <div class="container-fluid">
        <div class="desc">
            <div class="d-flex justify-content-center">
                <i class="fas fa-seedling"></i>
            </div>
            <div class="d-flex justify-content-center">
                <h3>Description</h3>
            </div>
            <div class="d-flex justify-content-center">
                <p>My name is Gita and I'm 19. I am currently pursuing Bachelor's degree in <a
                        href="http://www.cs.ui.ac.id/" target="_blank" style="color:lightsalmon">Computer
                        Science</a>
                    at the Faculty of Computer Science of
                    Universitas Indonesia (University of Indonesia).<br><br>
                    I'm a student who is eager to develop many skills and learn something new. I'm also motivated to
                    do
                    works that conduce positive
                    social impacts so that my knowledge can be beneficial for numerous people.<br><br>
                    I like cats and easy-to-eat food.</p>
            </div>

        </div>
    </div>
</section>

<!-- Education -->
<section>
    <div class="container-fluid">
        <div class="education">

            <div class="d-flex align-items-center justify-content-center">
                <i class="fas fa-book-open"></i>
                <h3>Education</h3>
            </div>

            <div class="d-flex align-items-center justify-content-center">
                <table>
                    <tr class="ui">
                        <td class="first-td">2019 - now</td>
                        <td class="second-td">
                            <p>Universitas Indonesia</p>
                            <p class="sub-td">Bachelor's degree in Computer Science</p>
                        </td>
                    </tr>
                    <tr class="sman3">
                        <td class="first-td">2015 - 2018</td>
                        <td class="second-td">
                            <p>SMA Negeri 3 Bandung</p>
                            <p class="sub-td">Mathematics and Natural Sciences</p>
                        </td>
                    </tr>
                    <tr class="nassa">
                        <td class="first-td">2006 - 2015</td>
                        <td class="second-td">SD-SMP Nassa School</td>
                    </tr>
                </table>
            </div>

        </div>

    </div>
    </div>
</section>

<!-- Hobbies -->
<section>
    <div class="container-fluid">
        <div class="hobby">

            <div class="d-flex align-items-center justify-content-center">
                <h3>My Hobbies</h3>
            </div>
            <div class="d-flex justify-content-center">
                <div class="hobbies">
                    <div class="row">
                        <div class="col-lg-4 px-4 py-4">
                            <i class="fab fa-connectdevelop"></i><br>
                            <h4>Surfing the internet</h4>
                        </div>
                        <div class="col-lg-4 px-4 py-4">
                            <i class="fas fa-bed"></i><br>
                            <h4>Sleeping</h4>
                        </div>
                        <div class="col-lg-4 px-4 py-4">
                            <i class="fas fa-atlas"></i><br>
                            <h4>Studying</h4>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<!-- Modal -->
<section>
    <div class="container-fluid">
        <div class="projects-modal">
            <button type="button" class="btn btn-projects" data-toggle="modal" data-target=".bd-example-modal-lg">
                My Projects
            </button>

            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">My Projects</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <!-- Carousel -->

                            <div id="projects-carousel" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#projects-carousel" data-slide-to="0" class="active"></li>
                                    <li data-target="#projects-carousel" data-slide-to="1"></li>
                                    <li data-target="#projects-carousel" data-slide-to="2"></li>
                                    <li data-target="#projects-carousel" data-slide-to="3"></li>
                                </ol>
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <h4>Budaya Knowledge Base Lite v2.0</h4>
                                        <img class="d-block w-100" src="{% static 'myprofile/images/budaya.png' %}"
                                            alt="Budaya Knowledge Base">
                                    </div>
                                    <div class="carousel-item">
                                        <h4>Timeline Web App</h4>
                                        <img class="d-block w-100" src="{% static 'myprofile/images/itfweb.png' %}" alt="Timeline Web App">
                                    </div>
                                    <div class="carousel-item">
                                        <h4>Secrets - Share your secrets anonymously</h4>
                                        <img class="d-block w-100" src="{% static 'myprofile/images/secrets.png' %}" alt="Secrets">
                                    </div>
                                    <div class="carousel-item">
                                        <h4>Simon Game - A color sequence game</h4>
                                        <img class="d-block w-100" src="{% static 'myprofile/images/simongame.png' %}" alt="Simon Game">
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#projects-carousel" role="button"
                                    data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#projects-carousel" role="button"
                                    data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <a class="btn" href="{% url 'myprofile:projects' %}">See projects page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

myprofile/templates/myprofile/navbar.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler1">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-brand"><a href="/">Gita's Website</a></div>

    <div class="collapse navbar-collapse" id="navbarToggler1">

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story1:story1index' %}">Story 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myprofile:projects' %}">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myprofile:time' %}">Time</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'matakuliah:matkuls' %}">Mata Kuliah</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'activities:activities' %}">Activities</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#reach">Contact</a>
            </li>
        </ul>

    </div>
</nav>

myprofile/templates/myprofile/time.html
{% extends 'myprofile/base.html' %}
{% block title %}Time{% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="header">
{% include 'myprofile/navbar.html' %}
    <br><br><br><br>
<h1>{{ time }}</h1>
</div></div>

{% endblock %}

story1/templates/story1/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>Gita's Website</title>
    <link href="https://fonts.googleapis.com/css?family=Abel|Kalam|La+Belle+Aurore|Montserrat|Open+Sans:300|Overpass"
        rel="stylesheet">

    <!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'story1/styles.css' %}">
</head>

<body><!-- foto kucing https://i.ibb.co/233rrsT/kocheng.jpg -->
    <div class="header">
        <a href="{% url 'myprofile:index' %}" class="fas fa-share"></a>
        <img src="https://drive.google.com/uc?id=1HgbDT_VrmozVHSkXlsoxh7k9vSaLHuN1" alt="Gita" width="200">
        <h1>Gita Permatasari Sujatmiko</h1>
        <p>1906400053</p>
        <p>CSUI 2019</p><br><br>
        <a class="btn btn-outline-light" href="#desc" role="button">Learn more about me</a>
    </div>

    <div id="desc" class="desc">
        <i class="fas fa-seedling"></i>
        <h3>Description</h3>
        <p>My name is Gita and I'm 19. I am currently pursuing Bachelor's degree in <a href="http://www.cs.ui.ac.id/" target="_blank" style="color:lightsalmon">Computer Science</a> 
            at the Faculty of Computer Science of
            Universitas Indonesia (University of Indonesia).</p>
        <p>I'm a student who is eager to develop many skills and learn something new. I'm also motivated to do works that conduce positive
            social impacts so that my knowledge can be beneficial for numerous people.</p>
        <p>I like cats and easy-to-eat food.</p>
    </div>

    <div class="education">

        <div class="d-flex align-items-center justify-content-center">
            <i class="fas fa-book-open"></i>
            <h3 class="montserrat">Education</h3>
        </div>

        <table>
            <tr class="ui">
                <td class="first-td">2019 - now</td>
                <td class="second-td"><p>Universitas Indonesia</p>
                    <p class="sub-td">Bachelor's degree in Computer Science</p></td>
            </tr>
            <tr class="sman3">
                <td class="first-td">2015 - 2018</td>
                <td class="second-td"><p>SMA Negeri 3 Bandung</p>
                    <p class="sub-td">Mathematics and Natural Sciences</p></td>
            </tr>
            <tr class="nassa">
                <td class="first-td">2006 - 2015</td>
                <td class="second-td">SD-SMP Nassa School</td>
            </tr>
        </table>

        </div>
            
        
    </div>

    <div class="hobby">
 
            <div class="d-flex align-items-center justify-content-center">
                <i class="fas fa-laptop-code"></i>
                <h3 class="montserrat">My Hobbies</h3>
            </div>
            <div class="hobbies">
                <div class="row">
                    <div class="col-lg-4 px-4 py-4">
                        <i class="fab fa-connectdevelop"></i><br>
                        <h4>Surfing the internet</h4>
                    </div>
                    <div class="col-lg-4 px-4 py-4">
                        <i class="fas fa-bed"></i><br>
                        <h4>Sleeping</h4>
                    </div> 
                    <div class="col-lg-4 px-4 py-4">
                        <i class="fas fa-atlas"></i><br>
                        <h4>Studying</h4>
                    </div>
                </div>
            </div>
            
    </div>

    <div id="reach" class="footer">
        <h3>Reach Me</h3>
        <a class="fab fa-instagram" href="https://instagram.com/gpersable" target="_blank"></a>
        <a class="fab fa-twitter" href="https://twitter.com/gpersable" target="_blank"></a>
        <a class="fab fa-telegram" href="https://t.me/gpersable" target="_blank"></a>
    </div>


    <!-- Bootstrap Scripts -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Smooth Scrolling Script -->
<script>
    $(document).ready(function () {

        // Add smooth scrolling to all links
        $("a").on('click', function (event) {
    
        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
       // Prevent default anchor click behavior
        event.preventDefault();
    
        // Store hash
        var hash = this.hash;
    
        // Using jQuery's animate() method to add smooth page scroll
        // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
        $('html, body').animate({
            scrollTop: $(hash).offset().top
        }, 600, function () {
    
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
        });
    } // End if
    });
    
    });
</script>
    
</body>

</html>